from fsm import TocMachine

machine = TocMachine(
    states=["user",
            "check",
            "dateInfo",
            "monthExpense",
            "monthIncome",
            "monthRatio",
            "monthAll",
            "weekExpense",
            "weekIncome",
            "weekRatio",
            "weekAll",
            "record",
            "action",
            "type",
            "value",
            "description"
            ],
    transitions=[
        {
            "trigger": "advance",
            "source": "user",
            "dest": "check",
            "conditions": "is_going_to_check",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "dateInfo",
            "conditions": "is_going_to_dateInfo",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "monthExpense",
            "conditions": "is_going_to_monthExpense",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "weekExpense",
            "conditions": "is_going_to_weekExpense",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "monthIncome",
            "conditions": "is_going_to_monthIncome",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "weekIncome",
            "conditions": "is_going_to_weekIncome",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "monthRatio",
            "conditions": "is_going_to_monthRatio",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "weekRatio",
            "conditions": "is_going_to_weekRatio",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "monthAll",
            "conditions": "is_going_to_monthAll",
        },
        {
            "trigger": "advance",
            "source": "check",
            "dest": "weekAll",
            "conditions": "is_going_to_weekAll",
        },
        {
            "trigger": "advance",
            "source": "user",
            "dest": "record",
            "conditions": "is_going_to_record",
        },
        {
            "trigger": "advance",
            "source": "record",
            "dest": "action",
            "conditions": "is_going_to_action",
        },
        {
            "trigger": "advance",
            "source": "action",
            "dest": "type",
            "conditions": "is_going_to_type",
        },
        {
            "trigger": "advance",
            "source": "type",
            "dest": "value",
            "conditions": "is_going_to_value",
        },
        {
            "trigger": "advance",
            "source": "value",
            "dest": "description",
            "conditions": "is_going_to_description",
        },
        {"trigger": "go_back",
         "source": ["dateInfo",
                    "monthExpense",
                    "monthIncome",
                    "monthRatio",
                    "monthAll",
                    "weekExpense",
                    "weekIncome",
                    "weekRatio",
                    "weekAll",
                    "description"
                    ],
         "dest": "user"
         },
    ],
    initial="user",
    auto_transitions=False,
    show_conditions=True,
)

machine.get_graph().draw("fsm.png", prog="dot", format="png")
